language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
    - php: 7.0
      env: DEPENDENCIES='low'
  fast_finish: true

before_install:
  - composer selfupdate
  - composer global require hirak/prestissimo

install:
  - if [ "$DEPENDENCIES" != "low" ]; then travis_retry composer update --no-progress --profile --prefer-dist --no-interaction; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --no-progress --profile --prefer-lowest --no-interaction; fi;

script:
   - ./vendor/bin/grumphp run
